# Generated by Django 2.2.1 on 2019-07-04 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Starfoil', 'Starfoil'), ('Super Rare', 'Super Rare'), ('Ultra Rare', 'Ultra Rare'), ('Secret Rare', 'Secret Rare')], max_length=15)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cardstock.card_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MonsterCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardstock.Card')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('atk', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('Aqua', 'Aqua'), ('Dinosaurier', 'Dinosaurier'), ('Donner', 'Donner'), ('Drache', 'Drache'), ('Fee', 'Fee'), ('Fels', 'Fels'), ('Fisch', 'Fisch'), ('Göttliches Ungeheuer', 'Göttliches Ungeheuer'), ('Geflügeltes Ungeheuer', 'Geflügeltes Ungeheuer'), ('Hexer', 'Hexer'), ('Insekt', 'Insekt'), ('Krieger', 'Krieger'), ('Maschine', 'Maschine'), ('Pflanze', 'Pflanze')], max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cardstock.card',),
        ),
        migrations.CreateModel(
            name='SpellCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardstock.Card')),
                ('type', models.CharField(choices=[('Ausrüstung', 'Ausrüstung'), ('Normal', 'Normal'), ('Permanent', 'Permanent'), ('Ritual', 'Ritual'), ('Schnell', 'Schnell'), ('Spielfeld', 'Spielfeld')], max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cardstock.card',),
        ),
        migrations.CreateModel(
            name='TrapCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardstock.Card')),
                ('type', models.CharField(choices=[('Konter', 'Konter'), ('Normal', 'Normal'), ('Permanent', 'Permanent')], max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cardstock.card',),
        ),
    ]
